# Generated by Django 3.2.5 on 2021-11-08 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_column='State', max_length=16)),
                ('city', models.CharField(db_column='City', max_length=32)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Weathertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, db_column='TypeName', max_length=32, null=True)),
            ],
            options={
                'db_table': 'weathertype',
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=64, null=True)),
                ('timezone', models.IntegerField(blank=True, db_column='TimeZone', null=True)),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.location')),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventdate', models.DateField(blank=True, db_column='EventDate', null=True)),
                ('severity', models.CharField(blank=True, db_column='Severity', max_length=16, null=True)),
                ('locationid', models.ForeignKey(db_column='LocationId', on_delete=django.db.models.deletion.DO_NOTHING, to='base.location')),
                ('weathertypeid', models.ForeignKey(db_column='WeatherTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='base.weathertype')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Usersearchhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searcheddate', models.DateField(blank=True, db_column='SearchedDate', null=True)),
                ('eventid', models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.CASCADE, to='base.event')),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usersearchhistory',
                'unique_together': {('userid', 'eventid')},
            },
        ),
    ]
